export const ActionTypes = {
    //auth
    USER_REGISTER_PENDING: "USER_REGISTER_PENDING",
    USER_LOGIN_PENDING: "USER_LOGIN_PENDING",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    SIGN_OUT: "SIGN_OUT",

    //users
    GET_USERS_PENDING: "GET_USERS_PENDING",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_ERROR: "GET_USERS_ERROR",
    DELETE_USERS: "DELETE_USERS",
    UPDATE_USERS: "UPDATE_USERS",
    SELECTED_USERS: "SELECTED_USERS",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
    SET_USER: "SET_USER",
};